/// Hydrates the client-side application after the initial server-side render.
///
/// This function is responsible for hydrating the client-side application,
/// which means taking over the static HTML generated by the server and making it interactive.
/// It is typically used in applications that employ server-side rendering (SSR) to improve
/// initial load performance and SEO.
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn hydrate() {
    use app::App;
    console_error_panic_hook::set_once();
    leptos::mount::hydrate_body(App);
}
